# Learning numpy

In [1]:
import numpy as np

## Array Transposition

In [2]:
arr = np.arange(50).reshape((10,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [3]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [4]:
np.dot(arr.T, arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [5]:
arr3d = np.arange(50).reshape((5,5,2))
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [6]:
arr3d.transpose(1,0,2)

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [7]:
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [8]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])

## Universal array funtions

In [9]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [11]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [12]:
A = np.random.randn(10)
A

array([-0.87710778,  0.46263975, -1.33300702, -0.25823283, -1.82036971,
       -1.00536289, -1.62990654, -0.4133664 , -0.02987565, -2.39903593])

In [13]:
B = np.random.randn(10)
B

array([ 0.291492  , -0.97056928,  0.2434622 , -0.45948799,  0.49967857,
        0.05748273, -0.7427697 ,  0.96412881,  0.52557917,  0.18272464])

### Binary funtions

In [14]:
np.add(A,B)

array([-0.58561578, -0.50792953, -1.08954482, -0.71772083, -1.32069114,
       -0.94788016, -2.37267624,  0.55076241,  0.49570352, -2.21631129])

In [15]:
np.maximum(A,B)

array([ 0.291492  ,  0.46263975,  0.2434622 , -0.25823283,  0.49967857,
        0.05748273, -0.7427697 ,  0.96412881,  0.52557917,  0.18272464])

In [16]:
website = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html'
import webbrowser
webbrowser.open(website)

True