# Learning numpy
#### save and load arrays

In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
np.save('myarray', arr)

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [6]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.savez('ziparray.npz',x=arr1,y=arr2)

In [8]:
archive_arrat = np.load('ziparray.npz')

In [9]:
archive_arrat['x']

array([0, 1, 2, 3, 4])

In [10]:
archive_arrat['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.savetxt('mytextarray.txt', arr,delimiter=',')

In [13]:
arr = np.loadtxt('mytextarray.txt', delimiter=',')
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])