# Learning numpy

In [1]:
import numpy as np  #import it

##   Creating array
  ### 1. from list.
        *In case you forget how to use the command, you can use (shift + Tab) to checkout how to use it.

In [2]:
list_1 = [1,2,3,4]

In [4]:
array_1 = np.array(list_1)
array_1

array([1, 2, 3, 4])

In [5]:
list_2 = [11,22,33,44]

In [6]:
lists = [list_1,list_2]

In [7]:
array_2 = np.array(lists)
array_2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

 ### 2. np.zeros()

In [8]:
array_3 = np.zeros(5)
array_3

array([ 0.,  0.,  0.,  0.,  0.])

In [9]:
array_4 = np.zeros([5,5])
array_4

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

### 3. np.ones()

In [10]:
array_5 = np.ones(5)
array_5

array([ 1.,  1.,  1.,  1.,  1.])

In [11]:
array_6 = np.ones([5,5])
array_6

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### 4. np.eye()

In [12]:
array_7 = np.eye(5)
array_7

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

### 5. np.arange()

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [16]:
array_8 = np.arange(5,50,2)
array_8

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])